import { Layout } from "@/components/layout/Layout";

export default function Terms() {
  return (
    <Layout>
      <section className="py-16">
        <div className="container max-w-3xl prose prose-sm">
          <h1 className="font-display text-4xl font-bold text-foreground">Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: March 25, 2026</p>

          <div className="mt-8 space-y-6 text-sm text-muted-foreground">
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
              <p>By using SWIFT (Smart Web Intelligence Fast Trading), you agree to these terms. If you do not agree, please do not use our platform.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground">2. Service Description</h2>
              <p>SWIFT provides an AI-powered agentic commerce platform that helps users discover, compare, and purchase products across multiple retailers through a conversational interface.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground">3. User Accounts</h2>
              <p>You are responsible for maintaining the confidentiality of your account. You agree to notify us immediately of any unauthorized access.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground">4. Orders and Payments</h2>
              <p>All prices are displayed in USD. SWIFT facilitates purchases across multiple retailers. Each retailer's individual terms may also apply to your purchase.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground">5. AI Recommendations</h2>
              <p>Product recommendations are generated by AI agents using transparent scoring. SWIFT does not guarantee product availability or pricing accuracy across retailers.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground">6. Limitation of Liability</h2>
              <p>SWIFT is not liable for any damages arising from the use of our platform. Our total liability shall not exceed the amount paid for the transaction in question.</p>
            </div>
            <div>
              <h2 className="font-display text-lg font-semibold text-foreground">7. Contact</h2>
              <p>For questions about these terms, contact us at +234 817 683 1186 or support@swift.com.</p>
            </div>
          </div>
        </div>
      </section>
    </Layout>
  );
}
